### PR TITLE
Remove obsolete configuration options

### LINKED ISSUE #145: Unused options in _configuration.py
While writing the docs for the options dict I found that some options in the configs are never used:

- fast_optim
- instant_plot
- grid_set_type

can they be removed?

### PR DESCRIPTION
**Pull request by otizonaizit**
Get rid of configuration options that are not used in the code.

This PR also removes the configuration option `stimulus_range`. For a rationale, see #143
The stimulus range is now only inferred from the data. Note that `width_min`, i.e. the lower bound of the width prior, can still be manually set. I am not sure if we should get rid of this too...

Fixes #145

### CODE REVIEW

**Comment by pberkes** [comment]
Thank you @otizonaizit , the changes look good. If we get rid of `stimulus_range`, I think some of the notebooks in `demo` need to be modified.

Are we sure we want to remove it? In #143, the problem was that the minimum width was set in a naive way, and we have improved that. Felix' comment was that the experiment should normally cover the range of plausible stimuli, so setting it by hand is not useful. OTOH, there might be cases where it's not possible to cover the full range, and still want to infer a sigmoid on the full range?

**Comment by otizonaizit** [comment]
btw, talking with a heavy user of psychometric function fitting libraries, I heard that it is difficult to imagine what sense an experiment would make where you do no sample the lower or higher part of the stimulus range but then want to fit a psychometric function and use that fit to claim something about thresholds and such...
If it is only about synthetic data, then we can keep the option internally as private but there's not need to advertise it as something useful. My fear is that people will follow the example codes where it is used and do the same mistake we were doing in #143 ...

**Comment by pberkes** [comment]
alright, let's do it then

**Comment by pberkes** [comment]
There's one last thing to do: remove `options["stimulus_range"] = stim_range` from the notebook `psignifit/demos/parameter_recovery_demo.ipynb`. It appears in two places. In principle, the rest should continue working as intended.

**Comment by otizonaizit** [comment]
@guillermoaguilar : before proceeding with the removal of `stimulus_range` I'd like to get your OK too.

**Comment by guillermoaguilar** [comment]
Yes sorry for the silence. 
`stim_range` is not really needed from the user perspective IMO. 
It should be private.


> There's one last thing to do: remove `options["stimulus_range"] = stim_range` from the notebook `psignifit/demos/parameter_recovery_demo.ipynb`. It appears in two places. In principle, the rest should continue working as intended.

In the rearrangement of documentation I've already removed it. But I haven't merge that yet. Leave that to me.

**Review by guillermoaguilar — APPROVED** [review]

**Comment by otizonaizit** [comment]
> There's one last thing to do: remove `options["stimulus_range"] = stim_range` from the notebook `psignifit/demos/parameter_recovery_demo.ipynb`. It appears in two places. In principle, the rest should continue working as intended.

well its' not so easy: that demo was already broken by #161 :

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[7], line 1
----> 1 assert np.isclose(res.parameter_estimate['lambda'], lambda_, atol=1e-4)

AttributeError: 'Result' object has no attribute 'parameter_estimate'
```

I think that the demos need to be checked again. I don't think it is a good idea for me to fix it in this PR, given that the thing is already broken...
By the way, it may make sense to still have a `Result.parameter_estimate` which is an alias of `Result.parameter_estimate_MAP`?

**Comment by guillermoaguilar** [comment]
> I think that the demos need to be checked again. I don't think it is a good idea for me to fix it in this PR, given that the thing is already broken... By the way, it may make sense to still have a `Result.parameter_estimate` which is an alias of `Result.parameter_estimate_MAP`?

Yes, it should be an alias for _MAP.
It's too complicated to ask the user to decide if to use `parameter_estimate_MAP`  or something else.... `parameter_estimate` should be the default.

**Comment by guillermoaguilar** [comment]
Then I guess I should merge the documentation changes and see what's broken.

**Review by guillermoaguilar — APPROVED** [review]

**Comment by otizonaizit** [comment]
OK, I made `stimulus_range` private. Which means that it can still be used internally with the name `Configuration._stimulus_range` but it is not advertised anywhere.
